# Inheritance Class

- Suatu class dapat mewarisi fungsi dari class lain. Jika sebuah object diciptakan menggunakan class yang mewarisi dari superclass, maka objek akan berisi method dari gabungan kedua kelas, yaitu kelas itu sendiri dan superclass.
- Suatu class dikatakan mewarisi class lain adalah ketika class tersebut memakai property atau method dari class lain. Misalnya dalam hal biologi, kita dapat memikirkan seorang anak yang mewarisi sifat-sifat tertentu dari orang tuanya. seperti, seorang anak dapat mewarisi warna mata atau tinggi orang tua.
- Class yang disebut class anak atau subclass mewarisi method dan variabel dari class induk atau kelas dasar atau parent class.
- Macam - macam inheritance :
<img src="img/macaminheritance.jpg">
- Contoh Inheritance :
<img src="img/inheritanceexample.png">

In [17]:
#Example 1
class User:
    
    def __init__(self, name):
        self.name = name
        
    def printName(self):
        print("Name = " + self.name)

class Programmer(User): #untuk memanggil attribut "name" maka membaca tentang Inheritance Super Class
    
    def __init__(self,lastname,name):
        self.lastname = lastname
        #User.__init__(self,name)
        super().__init__(name)
        
    def printLastName(self):
        print("LastName = " + self.lastname)
        
    def doPython(self):
        print("Programming Python")
        
class Programmer1(User):
    pass

brian = User("brian")
brian.printName()

diana1 = Programmer1("diana")
diana1.printName()

diana = Programmer("diana1","diana2")
diana.printName()
diana.printLastName()

Name = brian
Name = diana
Name = diana2
LastName = diana1

In [1]:
#Example 2
class Fish:
    def __init__(self, first_name, last_name="Fish",
                 skeleton="bone", eyelids=False):
        self.first_name = first_name
        self.last_name = last_name
        self.skeleton = skeleton
        self.eyelids = eyelids

    def swim(self):
        print("The fish is swimming.")

    def swim_backwards(self):
        print("The fish can swim backwards.")


class Trout(Fish):
    pass

class Clownfish(Fish):

    def live_with_anemone(self):
        print("The clownfish is coexisting with sea anemone.")
        

terry = Trout("Terry")
print(terry.first_name + " " + terry.last_name)
print(terry.skeleton)
print(terry.eyelids)
terry.swim()
terry.swim_backwards()

terry1 = Trout("TerryS", "SmallFish", "no bone", True)
print(terry1.first_name + " " + terry.last_name)
print(terry1.skeleton)
print(terry1.eyelids)
terry1.swim()
terry1.swim_backwards()

casey = Clownfish("Casey")
print(casey.first_name + " " + casey.last_name)
casey.swim()
casey.live_with_anemone()

Terry Fish
bone
False
The fish is swimming.
The fish can swim backwards.
TerryS Fish
no bone
True
The fish is swimming.
The fish can swim backwards.
Casey Fish
The fish is swimming.
The clownfish is coexisting with sea anemone.

In [4]:
from datetime import date

class Orang:
    def __init__(self, nama):
        self.nama = nama
    def printNama(self):
        print("Name = " + self.nama)
        
class Mahasiswa(Orang):
    def __init__(self,nama,npm):
        super().__init__(nama)
        self.npm = npm
    def printNPM(self):
        print("NPM = " + self.npm)
    def semester(self):
        tang = self.npm[0:2]
        tang = int("20"+str(tang)) #tahun angkatan
        today = date.today()
        if today.month == (2,3,4,5,6,7):
            smstr = 2
        else:
            smstr = 1
        tak=int(str(today.year) + str(smstr)) #tahun akademik
        if tak %2 != 0:
            a=((tak+10)-1)/10
            b=a-tang
            c=(b*2)-1
            print("Semester = ", c)
        else:
            a=((tak+10)-2)/10
            b=a-tang
            c=(b*2)-2
            print("Semester = ", c)

class Pegawai(Orang):
    def __init__(self,nama,nip):
        super().__init__(nama)
        self.nip = nip
    def printNIP(self):
        print("NIP = " + self.nip)
        
class Dosen(Pegawai):
    def __init__(self,nama, nip, nidn):
        super().__init__(nama, nip)
        self.nidn = nidn
    def printNIDN(self):
        print("NIDN = " + self.nidn)

class Karyawan(Pegawai):
    pass
        
hendrik = Mahasiswa("Hendrik", "170411100057\n")
hendrik.printNama()
hendrik.printNPM()

buarik = Dosen("Arik Kurniawati", "00071", "000076\n")
buarik.printNama()
buarik.printNIP()
buarik.printNIDN()

karyawan = Karyawan("Karyawan1", "000079\n")
karyawan.printNama()
karyawan.printNIP()

Name = Hendrik
NPM = 170411100057
Semester =  3.0

In [24]:
class User:
    
    def __init__(self, firstName):
        self.firstName = firstName
        
    def printName(self):
        print("Firstname = " + self.firstName)

class Programmer(User):
    
    def __init__(self,firstName,lastName):
        super().__init__(firstName)
        self.lastName = lastName
        
    def printLastName(self):
        print("LastName = " + self.lastName)

hendrik = User("Hendrik")
hendrik.printName()
hendrik2 = Programmer("M. Hendrik","Wicaksono")
hendrik2.printName()
hendrik2.printLastName()

rohman = User("Rohman")
rohman.printName()
rohman2 = Programmer("Rohman","Fathoni")
rohman2.printName()
rohman2.printLastName()

Firstname = Hendrik
Firstname = M. Hendrik
LastName = Wicaksono
Firstname = Rohman
Firstname = Rohman
LastName = Fathoni

In [1]:
from datetime import date

class Orang:
    def __init__(self, nama):
        self.nama = nama
        
class Mahasiswa(Orang):
    def __init__(self,nama,npm):
        super().__init__(nama)
        self.npm = npm
    def printNama(self):
        print("\nNama Mahasiswa = " + self.nama)
    def printNPM(self):
        print("NPM = " + self.npm)
    def semester(self):
        tang = self.npm[0:2]
        tang = int("20"+str(tang)) #tahun angkatan
        today = date.today()
        if today.month == (2,3,4,5,6,7):
            smstr = 2
        else:
            smstr = 1
        tak=int(str(today.year) + str(smstr)) #tahun akademik
        if tak %2 != 0:
            a=((tak+10)-1)/10
            b=a-tang
            c=(b*2)-1
            print("Semester = " + str(c))
        else:
            a=((tak+10)-2)/10
            b=a-tang
            c=(b*2)-2
            print("Semester = " + str(c))
            
class Pegawai(Orang):
    def __init__(self,nama,nip):
        super().__init__(nama)
        self.nip = nip
    
    def printNIP(self):
        print("NIP = " + self.nip)
        
class Dosen(Pegawai):
    def __init__(self,nama, nip, nidn):
        super().__init__(nama, nip)
        self.nidn = nidn
    def printNama(self):
        print("\nNama Dosen = " + self.nama)
    def printNIDN(self):
        print("NIDN = " + self.nidn)

class Karyawan(Pegawai):
    def printNama(self):
        print("\nNama Karyawan = " + self.nama)
        
#Class Mahasiswa
hendrik = Mahasiswa("Hendrik", "170411100057")
hendrik.printNama()
hendrik.printNPM()
hendrik.semester()

rohman = Mahasiswa("Rohman", "170411100089")
rohman.printNama()
rohman.printNPM()
rohman.semester()

#Class Dosen
dosen1 = Dosen("Arik Kurniawati, S.Kom., M.T.", "19780309 200312 2 009", "0009037802")
dosen1.printNama()
dosen1.printNIP()
dosen1.printNIDN()

#Class Karyawan
karyawan1 = Karyawan("Agus", "19750806 200501 1 006")
karyawan1.printNama()
karyawan1.printNIP()

karyawan2 = Karyawan("Budi", "19750806 200501 1 012")
karyawan2.printNama()
karyawan2.printNIP()

Nama Mahasiswa = Hendrik
NPM = 170411100057
Semester = 3.0

Nama Mahasiswa = Rohman
NPM = 170411100089
Semester = 3.0

Nama Dosen = Arik Kurniawati, S.Kom., M.T.
NIP = 19780309 200312 2 009
NIDN = 0009037802

Nama Karyawan = Agus
NIP = 19750806 200501 1 006

Nama Karyawan = Budi
NIP = 19750806 200501 1 012

In [2]:
class User:
    
    def __init__(self, firstName):
        self.firstName = firstName
        
    def printName(self):
        print("Firstname = " + self.firstName)

class Programmer(User):
    
    def __init__(self,firstName,lastName):
        User.__init__(self,firstName)
        self.lastName = lastName
        
    def printLastName(self):
        print("LastName = " + self.lastName)

hendrik = User("Hendrik")
hendrik.printName()
hendrik2 = Programmer("M. Hendrik","Wicaksono")
hendrik2.printName()
hendrik2.printLastName()

rohman = User("Rohman")
rohman.printName()
rohman2 = Programmer("Rohman","Fathoni")
rohman2.printName()
rohman2.printLastName()

Firstname = Hendrik
Firstname = M. Hendrik
LastName = Wicaksono
Firstname = Rohman
Firstname = Rohman
LastName = Fathoni

In [3]:
from datetime import date

class Orang:
    def __init__(self, nama):
        self.nama = nama
        
class Mahasiswa(Orang):
    def __init__(self,nama,npm):
        Orang.__init__(self,nama)
        self.npm = npm
    def printNama(self):
        print("\nNama Mahasiswa = " + self.nama)
    def printNPM(self):
        print("NPM = " + self.npm)
    def semester(self):
        tang = self.npm[0:2]
        tang = int("20"+str(tang)) #tahun angkatan
        today = date.today()
        if today.month == (2,3,4,5,6,7):
            smstr = 2
        else:
            smstr = 1
        tak=int(str(today.year) + str(smstr)) #tahun akademik
        if tak %2 != 0:
            a=((tak+10)-1)/10
            b=a-tang
            c=(b*2)-1
            print("Semester = " + str(c))
        else:
            a=((tak+10)-2)/10
            b=a-tang
            c=(b*2)-2
            print("Semester = " + str(c))
            
class Pegawai(Orang):
    def __init__(self,nama,nip):
        Orang.__init__(self,nama)
        self.nip = nip
    
    def printNIP(self):
        print("NIP = " + self.nip)
        
class Dosen(Pegawai):
    def __init__(self,nama, nip, nidn):
        Pegawai.__init__(self,nama, nip)
        self.nidn = nidn
    def printNama(self):
        print("\nNama Dosen = " + self.nama)
    def printNIDN(self):
        print("NIDN = " + self.nidn)

class Karyawan(Pegawai):
    def printNama(self):
        print("\nNama Karyawan = " + self.nama)
        
#Class Mahasiswa
hendrik = Mahasiswa("Hendrik", "170411100057")
hendrik.printNama()
hendrik.printNPM()
hendrik.semester()

rohman = Mahasiswa("Rohman", "170411100089")
rohman.printNama()
rohman.printNPM()
rohman.semester()

#Class Dosen
dosen1 = Dosen("Arik Kurniawati, S.Kom., M.T.", "19780309 200312 2 009", "0009037802")
dosen1.printNama()
dosen1.printNIP()
dosen1.printNIDN()

#Class Karyawan
karyawan1 = Karyawan("Agus", "19750806 200501 1 006")
karyawan1.printNama()
karyawan1.printNIP()

karyawan2 = Karyawan("Budi", "19750806 200501 1 012")
karyawan2.printNama()
karyawan2.printNIP()

Nama Mahasiswa = Hendrik
NPM = 170411100057
Semester = 3.0

Nama Mahasiswa = Rohman
NPM = 170411100089
Semester = 3.0

Nama Dosen = Arik Kurniawati, S.Kom., M.T.
NIP = 19780309 200312 2 009
NIDN = 0009037802

Nama Karyawan = Agus
NIP = 19750806 200501 1 006

Nama Karyawan = Budi
NIP = 19750806 200501 1 012